const HE: Record<string, string> = {
  // CONMEBOL
  'Argentina': 'ארגנטינה',
  'Brazil': 'ברזיל',
  'Colombia': 'קולומביה',
  'Uruguay': 'אורוגוואי',
  'Ecuador': 'אקוודור',
  'Venezuela': 'ונצואלה',
  'Chile': 'צ׳ילה',
  'Peru': 'פרו',
  'Paraguay': 'פרגוואי',
  'Bolivia': 'בוליביה',

  // UEFA
  'Germany': 'גרמניה',
  'France': 'צרפת',
  'Spain': 'ספרד',
  'England': 'אנגליה',
  'Portugal': 'פורטוגל',
  'Netherlands': 'הולנד',
  'Belgium': 'בלגיה',
  'Italy': 'איטליה',
  'Croatia': 'קרואטיה',
  'Switzerland': 'שווייץ',
  'Denmark': 'דנמרק',
  'Poland': 'פולין',
  'Sweden': 'שבדיה',
  'Norway': 'נורבגיה',
  'Finland': 'פינלנד',
  'Iceland': 'איסלנד',
  'Austria': 'אוסטריה',
  'Hungary': 'הונגריה',
  'Turkey': 'טורקיה',
  'Greece': 'יוון',
  'Romania': 'רומניה',
  'Serbia': 'סרביה',
  'Ukraine': 'אוקראינה',
  'Slovakia': 'סלובקיה',
  'Czech Republic': 'צ׳כיה',
  'Czechia': 'צ׳כיה',
  'Scotland': 'סקוטלנד',
  'Wales': 'ויילס',
  'Albania': 'אלבניה',
  'Georgia': 'גיאורגיה',
  'Bosnia and Herzegovina': 'בוסניה',
  'Bosnia & Herzegovina': 'בוסניה',
  'North Macedonia': 'מקדוניה',
  'Slovenia': 'סלובניה',
  'Bulgaria': 'בולגריה',
  'Kosovo': 'קוסובו',
  'Montenegro': 'מונטנגרו',
  'Moldova': 'מולדובה',
  'Russia': 'רוסיה',

  // CONCACAF
  'United States': 'ארה״ב',
  'USA': 'ארה״ב',
  'Canada': 'קנדה',
  'Mexico': 'מקסיקו',
  'Panama': 'פנמה',
  'Costa Rica': 'קוסטה ריקה',
  'Honduras': 'הונדורס',
  'Jamaica': 'ג׳מייקה',
  'Trinidad and Tobago': 'טרינידד',
  'Trinidad & Tobago': 'טרינידד',
  'El Salvador': 'אל סלבדור',
  'Guatemala': 'גואטמלה',
  'Cuba': 'קובה',
  'Haiti': 'האיטי',
  'Suriname': 'סורינאם',
  'Curacao': 'קוראסאו', 'Curaçao': 'קוראסאו', 'Curaçao PR': 'קוראסאו',
  'Guyana': 'גיאנה',

  // AFC
  'Japan': 'יפן',
  'South Korea': 'ק. הדרומית',
  'Korea Republic': 'ק. הדרומית',
  'Australia': 'אוסטרליה',
  'Saudi Arabia': 'סעודיה',
  'Iran': 'איראן',
  'Iraq': 'עיראק',
  'Jordan': 'ירדן',
  'Uzbekistan': 'אוזבקיסטן',
  'China': 'סין',
  'China PR': 'סין',
  'Indonesia': 'אינדונזיה',
  'Qatar': 'קטאר',
  'UAE': 'איחוד האמירויות',
  'United Arab Emirates': 'איחוד האמירויות',
  'Thailand': 'תאילנד',
  'Vietnam': 'וייטנאם',
  'Bahrain': 'בחריין',
  'India': 'הודו',
  'Kyrgyz Republic': 'קירגיזסטן',
  'Tajikistan': 'טג׳יקיסטן',
  'Oman': 'עומאן',
  'Kuwait': 'כווית',
  'Syria': 'סוריה',
  'Lebanon': 'לבנון',
  'Palestine': 'פלסטין',

  // CAF
  'Morocco': 'מרוקו',
  'Nigeria': 'ניגריה',
  'Egypt': 'מצרים',
  'Senegal': 'סנגל',
  'Ghana': 'גאנה',
  'Cameroon': 'קמרון',
  'Tunisia': 'תוניסיה',
  'Algeria': 'אלג׳יריה',
  "Côte d'Ivoire": 'חוף השנהב',
  'Ivory Coast': 'חוף השנהב',
  'Mali': 'מאלי',
  'South Africa': 'דרום אפריקה',
  'DR Congo': 'קונגו',
  'Congo DR': 'קונגו',
  'Democratic Republic of Congo': 'קונגו',
  'Cape Verde': 'קייפ ורדה',
  'Zambia': 'זמביה',
  'Zimbabwe': 'זימבבואה',
  'Kenya': 'קניה',
  'Guinea': 'גינאה',
  'Uganda': 'אוגנדה',
  'Angola': 'אנגולה',
  'Ethiopia': 'אתיופיה',
  'Comoros': 'קומורו',
  'Namibia': 'נמיביה',
  'Mauritania': 'מאוריטניה',
  'Benin': 'בנין',

  // OFC
  'New Zealand': 'ניו זילנד',

  // ── ליגת העל הישראלית ────────────────────────────────────
  'Maccabi Tel Aviv': 'מכבי ת"א',
  'Hapoel Beer Sheva': 'הפועל ב"ש',
  "Hapoel Be'er Sheva": 'הפועל ב"ש',
  'Hapoel Beer-Sheva': 'הפועל ב"ש',
  'Maccabi Haifa': 'מכבי חיפה',
  'Hapoel Tel Aviv': 'הפועל ת"א',
  'Beitar Jerusalem': 'בית"ר י-ם',
  'Hapoel Jerusalem': 'הפועל י-ם',
  'Bnei Sakhnin': 'בני סכנין',
  'Maccabi Petah Tikva': 'מכבי פ"ת',
  "Maccabi Petah-Tikva": 'מכבי פ"ת',
  'Ironi Kiryat Shmona': 'עירוני ק"ש',
  'Hapoel Haifa': 'הפועל חיפה',
  'Bnei Yehuda': 'בני יהודה',
  'FC Ashdod': 'א.ס. אשדוד',
  'MS Ashdod': 'א.ס. אשדוד',
  'Maccabi Bnei Raina': 'מכבי בני ריינה',
  'Bnei Raina': 'בני ריינה',
  'Hapoel Nof Hagalil': 'הפועל נוף הגליל',
  'Ironi Nof Hagalil': 'עירוני נוף הגליל',
  'Hapoel Hadera': 'הפועל חדרה',
  'Maccabi Netanya': 'מכבי נתניה',
  'Ironi Tiberias': 'עירוני טבריה',
  'Hapoel Petah Tikva': 'הפועל פ"ת',
  'Maccabi Umm al-Fahm': 'מכבי אום אל-פחם',
  'Ironi Tel Aviv': 'עירוני ת"א',
};

export function teamHe(name: string): string {
  return HE[name] ?? name;
}
