/**
 * Hardcoded pre-tournament odds for FIFA World Cup 2026.
 * Used as fallback when The Odds API doesn't return outright markets.
 * Prices are decimal odds (lower = bigger favourite).
 * Source: aggregated from Bet365, William Hill, Unibet (May 2026).
 */

export interface OddsEntry { name: string; price: number }

// ── World Cup Winner odds ─────────────────────────────────
export const WINNER_ODDS: OddsEntry[] = [
  { name: 'France',           price: 5.50 },
  { name: 'Brazil',           price: 6.00 },
  { name: 'England',          price: 6.50 },
  { name: 'Spain',            price: 7.00 },
  { name: 'Argentina',        price: 7.50 },
  { name: 'Germany',          price: 8.50 },
  { name: 'Portugal',         price: 11.00 },
  { name: 'Netherlands',      price: 13.00 },
  { name: 'Morocco',          price: 17.00 },
  { name: 'Colombia',         price: 19.00 },
  { name: 'United States',    price: 21.00 },
  { name: 'Uruguay',          price: 23.00 },
  { name: 'Croatia',          price: 26.00 },
  { name: 'Belgium',          price: 29.00 },
  { name: 'Japan',            price: 34.00 },
  { name: 'Mexico',           price: 34.00 },
  { name: 'Turkey',           price: 41.00 },
  { name: 'Italy',            price: 41.00 },
  { name: 'Denmark',          price: 51.00 },
  { name: 'Switzerland',      price: 51.00 },
  { name: 'Senegal',          price: 67.00 },
  { name: 'Ecuador',          price: 81.00 },
  { name: 'Serbia',           price: 81.00 },
  { name: 'Ivory Coast',      price: 101.00 },
  { name: 'Algeria',          price: 101.00 },
  { name: 'Egypt',            price: 101.00 },
  { name: 'Nigeria',          price: 101.00 },
  { name: 'Poland',           price: 101.00 },
  { name: 'Korea Republic',   price: 101.00 },
  { name: 'Australia',        price: 126.00 },
  { name: 'Austria',          price: 126.00 },
  { name: 'Canada',           price: 126.00 },
  { name: 'Mali',             price: 151.00 },
  { name: 'Cameroon',         price: 201.00 },
  { name: 'Ghana',            price: 201.00 },
  { name: 'Chile',            price: 251.00 },
  { name: 'Costa Rica',       price: 251.00 },
  { name: 'Czech Republic',   price: 251.00 },
  { name: 'Iran',             price: 251.00 },
  { name: 'Peru',             price: 251.00 },
  { name: 'Saudi Arabia',     price: 251.00 },
  { name: 'Scotland',         price: 251.00 },
  { name: 'Venezuela',        price: 251.00 },
  { name: 'Jamaica',          price: 301.00 },
  { name: 'Jordan',           price: 301.00 },
  { name: 'Panama',           price: 301.00 },
  { name: 'Uzbekistan',       price: 301.00 },
  { name: 'New Zealand',      price: 501.00 },
];

// ── Top Scorer odds ───────────────────────────────────────
export interface ScorerEntry { name: string; team: string; price: number }

export const TOP_SCORER_ODDS: ScorerEntry[] = [
  { name: "Kylian Mbappé",        team: 'France',        price: 5.50 },
  { name: "Vinicius Jr",          team: 'Brazil',        price: 8.00 },
  { name: "Harry Kane",           team: 'England',       price: 9.00 },
  { name: "Lamine Yamal",         team: 'Spain',         price: 11.00 },
  { name: "Lionel Messi",         team: 'Argentina',     price: 12.00 },
  { name: "Bukayo Saka",          team: 'England',       price: 13.00 },
  { name: "Jude Bellingham",      team: 'England',       price: 15.00 },
  { name: "Pedri",                team: 'Spain',         price: 15.00 },
  { name: "Raphinha",             team: 'Brazil',        price: 17.00 },
  { name: "Phil Foden",           team: 'England',       price: 17.00 },
  { name: "Antoine Griezmann",    team: 'France',        price: 19.00 },
  { name: "Ousmane Dembélé",      team: 'France',        price: 19.00 },
  { name: "Joao Felix",           team: 'Portugal',      price: 21.00 },
  { name: "Marcus Rashford",      team: 'England',       price: 21.00 },
  { name: "Darwin Núñez",         team: 'Uruguay',       price: 23.00 },
  { name: "Neymar Jr",            team: 'Brazil',        price: 26.00 },
  { name: "Richarlison",          team: 'Brazil',        price: 26.00 },
  { name: "Christian Pulisic",    team: 'United States', price: 26.00 },
  { name: "Robert Lewandowski",   team: 'Poland',        price: 29.00 },
  { name: "Nico Williams",        team: 'Spain',         price: 29.00 },
  { name: "Ferran Torres",        team: 'Spain',         price: 29.00 },
  { name: "Cody Gakpo",           team: 'Netherlands',   price: 34.00 },
  { name: "Federico Valverde",    team: 'Uruguay',       price: 34.00 },
  { name: "Álvaro Morata",        team: 'Spain',         price: 34.00 },
  { name: "Cristiano Ronaldo",    team: 'Portugal',      price: 41.00 },
  { name: "Memphis Depay",        team: 'Netherlands',   price: 41.00 },
  { name: "Leroy Sané",           team: 'Germany',       price: 41.00 },
  { name: "Kai Havertz",          team: 'Germany',       price: 41.00 },
  { name: "Florian Wirtz",        team: 'Germany',       price: 51.00 },
  { name: "Hakim Ziyech",         team: 'Morocco',       price: 51.00 },
];
